gdrive:
  clientID: '617805940796-jrchbkhp8etbik42k4v6v6mgk5i27bdq.apps.googleusercontent.com'
  clientSecret: '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'
  redirectURL: 'http://localhost'
  mainFolderId: '1UtkqzAXvtcjNYlIYjBZpBdo1M0uQ7ovE'
  accessToken: 'ya29.a0AfB_byAxpr2ubhMRbQ7PsAkW2Y7_PpqyXSBlVZjChd9B_3_s4feNAVUSdArGNjnEqmUhXk9c-AGxG8fccFqrsveOQxo3JkIsIJ-Z5xQzCrUaZt52FS8EMc3JGYkZU3doIi1kJUDADfy7FnZTSdhrkz6mshkkx1zYv3vaaCgYKAcESARMSFQHGX2MiSIb2sIqoBf_EkuVDSe-9ew0171'
  refreshToken: '1//0esEDiBDmknFwCgYIARAAGA4SNwF-L9IrCL-LI9lFjXCZlgPbpqOf6OP9Kr62N507jPz7Yifpo10bMakPLbvwzrGd1lG9JRfS_f0'
  apikey: 'AIzaSyCRU9NhMBl1B9OKXC6j9WoCu130af1yBTU'
