gdrive:
  clientID: '617805940796-jrchbkhp8etbik42k4v6v6mgk5i27bdq.apps.googleusercontent.com'
  clientSecret: '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'
  redirectURL: 'http://localhost'
  mainFolderId: '1UtkqzAXvtcjNYlIYjBZpBdo1M0uQ7ovE'
  accessToken: 'ya29.a0AfB_byCOXs5tojI_6QMetslMqBvRf6scb4p5VFdJmbMHwqhqLj8EmuuKCGJ6r3gsZrydhrf866dustDI21AdXM-zF-Ptu5BCy0WxPntycq-9OULCdKb6lkBaMqLG2VsLi9KOKvMLVy_YYY4wrgFe30In2SUrPOYlLYMAaCgYKAaMSARMSFQHGX2Mihucnp0dt18jIvaXN2422-A0171'
  refreshToken: '1//0e6h_hujRwNN6CgYIARAAGA4SNwF-L9IrgcAqve1y7iONCojoReh3xAEY3Y2tsLlfDn5X8GlTQ3T8wdFcHorr6_KvOImEDTcd8fM'
  apikey: 'AIzaSyCRU9NhMBl1B9OKXC6j9WoCu130af1yBTU'
